name: "Nextcloud"
version: "31.0.0.18"
slug: "nextcloud"
description: "A safe home for all your data with Nextcloud"
url: "https://github.com/x9132706292/hassos-addons/tree/main/hassos-addon-nextcloud"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
startup: "application"
boot: "auto"
ports:
  80/tcp: 8080
ports_description:
  80/tcp: "Web interface for Nextcloud"
map:
  - share:rw
options:
  trusted_domains:
    - "localhost"
  admin_user: "admin"
  admin_password: "nextcloud"
  db_type: "pgsql"
  db_host: "77b2833f-timescaledb"
  db_port: "5432"
  db_name: "nextcloud"
  db_user: "nextcloud"
  db_password: "your_secure_password"
  data_dir: "/share/nextcloud"
schema:
  trusted_domains:
    - "str"
  admin_user: "str"
  admin_password: "password"
  db_type: "list(mysql|pgsql|sqlite|oci)"
  db_host: "str"
  db_port: "int"
  db_name: "str"
  db_user: "str"
  db_password: "password"
  data_dir: "str"
webui: "http://[HOST]:[PORT:8080]"
