name: "Nextcloud"
version: "31.0.0"
slug: "nextcloud"
description: "A safe home for all your data with Nextcloud"
url: "https://github.com/x9132706292/hassos-addons/tree/main/hassos-addon-nextcloud"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
startup: "application"
boot: "auto"
ports:
  80/tcp: 8080
ports_description:
  80/tcp: "Web interface for Nextcloud"
map:
  - share:rw
options:
  NEXTCLOUD_ADMIN_USER: "hassio"
  NEXTCLOUD_ADMIN_PASSWORD": "nextcloud"
  NEXTCLOUD_TRUSTED_DOMAINS: "homeassistant.local"
  TRUSTED_PROXIES": "127.0.0.1 172.30.33.0/24 192.168.1.1"
  POSTGRES_DB: "nextcloud"
  POSTGRES_USER: "nextcloud"
  POSTGRES_PASSWORD: "your_secure_password"
  POSTGRES_HOST: "77b2833f-timescaledb" 
schema:
  NEXTCLOUD_ADMIN_USER: "str"
  NEXTCLOUD_ADMIN_PASSWORD": "password"
  NEXTCLOUD_TRUSTED_DOMAINS: "str"
  TRUSTED_PROXIES": "str"
  POSTGRES_DB: "str"
  POSTGRES_USER: "str"
  POSTGRES_PASSWORD: "password"
  POSTGRES_HOST: "str"
webui: "http://[HOST]:[PORT:8080]"
