name: "Nextcloud"
version: "31.0.0"
slug: "nextcloud"
description: "A safe home for all your data with Nextcloud"
url: "https://github.com/x9132706292/hassos-addons/tree/main/hassos-addon-nextcloud"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
startup: "application"
boot: "auto"
ports:
  80/tcp: 8080
ports_description:
  80/tcp: "Web interface for Nextcloud"
map:
  - share:rw
options:
  TRUSTED_PROXIES: "127.0.0.1 172.30.33.0/24 192.168.1.1"
schema:
  TRUSTED_PROXIES: "str"
webui: "http://[HOST]:[PORT:8080]"
