name: "Nextcloud"
version: "31.0.0"
slug: "nextcloud"
description: "A safe home for all your data with Nextcloud"
url: "https://github.com/x9132706292/hassos-addons/tree/main/hassos-addon-nextcloud"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
startup: "application"
boot: "auto"
ports:
  8080/tcp: 8080
  9980/tcp: 9980
ports_description:
  8080/tcp: "Web interface for Nextcloud"
  9980/tcp: "Collabora Online server"
map:
  - share:rw
webui: "http://[HOST]:[PORT:8080]"
