name: "Nextcloud"
version: "1.0.0"
slug: "nextcloud"
description: "A safe home for all your data with Nextcloud"
url: "https://github.com/x9132706292/hassos-addons/tree/main/hassos-addon-nextcloud"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
startup: "application"
boot: "auto"
ports:
  80/tcp: 8080
ports_description:
  80/tcp: "Web interface for Nextcloud"
map:
  - share:rw
options:
  admin_user: "nextcloud"
  admin_password: null
  db_host: "77b2833f-timescaledb"
  db_name: "nextcloud"
  db_user: "nextcloud"
  db_password: null
schema:
  admin_user: "str"
  admin_password: "password"
  db_host: "str"
  db_name: "str"
  db_user: "str"
  db_password: "password"
