name: "Nextcloud"
version: "31.0.18"
slug: "nextcloud"
description: "A safe home for all your data with Nextcloud"
url: "https://github.com/x9132706292/hassos-addons/tree/main/hassos-addon-nextcloud/"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
startup: "application"
boot: "auto"
webui: "http://[HOST]:[PORT:8080]"
ports:
  80/tcp: 8080
ports_description:
  80/tcp: "Web interface for Nextcloud"
map:
  - share:rw
options:
  trusted_domains: "localhost"
schema:
  trusted_domains: "str"
