name: "slash"
version: "1.0.0"
slug: "slash"
description: "An open source, self-hosted platform for sharing and managing your most frequently used links. Easily create customizable, human-readable shortcuts to streamline your link management."
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
url: "https://github.com/x9132706292/hassos-addons/"
boot: "auto"
options:
  SLASH_DRIVER: "postgres"
  SLASH_DSN: "postgresql://slash:password@77b2833f-timescaledb:5432/slash?sslmode=disable"
schema:
  SLASH_DRIVER: str
  SLASH_DSN: str
ports:
  "5231/tcp": 5231
map:
  - addon_config:rw
  - data:rw
