name: "Teable Community Edition"
version: "1.0.0"
slug: "teable"
description: "Teable Community Edition for Home Assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: "application"
boot: "auto"
options:
  POSTGRES_HOST: "77b2833f-timescaledb"
  POSTGRES_PORT: 5432
  POSTGRES_DB: "teable"
  POSTGRES_USER: "teable"
  POSTGRES_PASSWORD: "teable"
  REDIS_HOST: "2118a69b-redis"
  REDIS_PORT: 6379
  REDIS_DB: 0
  REDIS_PASSWORD: "redis_password"
  PUBLIC_ORIGIN: "http://127.0.0.1:3000"
schema:
  POSTGRES_HOST: str
  POSTGRES_PORT: int(1,65534)
  POSTGRES_DB: str
  POSTGRES_USER: str
  POSTGRES_PASSWORD: password
  REDIS_HOST: str
  REDIS_PORT: int(1,65534)
  REDIS_DB: int
  REDIS_PASSWORD: password
  PUBLIC_ORIGIN: str
ports:
  "3000/tcp": 3000
webui: "http://[HOST]:[PORT:3000]"
