name: "shlink"
version: "5"
slug: "shlink"
description: "The definitive self-hosted URL shortener"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
url: "https://github.com/x9132706292/hassos-addons/"
boot: "auto"
options:
  DB_DRIVER: "postgres"
  DB_HOST: "77b2833f-timescaledb"
  DB_PORT: 5432
  DB_NAME: "shlink"
  DB_USER: "shlink"
  DB_PASSWORD: "shlink"
  DEFAULT_DOMAIN: "s.test"
  GEOLITE_LICENSE_KEY: "kjh23ljkbndskj345"
  IS_HTTPS_ENABLED: false
schema:
  DB_DRIVER: list(mysql|maria|postgres|mssql)
  DB_HOST: str
  DB_PORT: int(1,65534)
  DB_NAME: str
  DB_USER: str
  DB_PASSWORD: password
  DEFAULT_DOMAIN: str
  GEOLITE_LICENSE_KEY: str?
  IS_HTTPS_ENABLED: bool
ports:
  "8080/tcp": 8080
map:
  - addon_config:rw
  - data:rw
