name: "Teable "
version: "1.0.0"
slug: "teable-db"
description: ""
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "once"
boot: "manual"
options:
  prisma_database_url: "postgres://teable:teable@77b2833f-timescaledb:5432/teable"
schema:
  prisma_database_url: str
ports: {}
