name: "Redis"
version: "7.2.4"
slug: "redis"
description: "Redis server for Home Assistant"
url: "https://github.com/x9132706292/hassos-addons/tree/main/hassio-addon-redis"
startup: "services"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  6379/tcp: 6379
ports_description:
  6379/tcp: "Redis server port"
options:
  password: null
schema:
  password: password?
