name: "ByeDPI"
version: "2024"
slug: "byedpi"
description: "Docker - контейнер для обхода DPI. поднимает socks-proxy на 999 порту. \nДля работы необходимо установить Docker. \nКонтейнер для архитектуры x86_x64. Если у вашего устройства другая архитектура, то перед сборкой поменяйте бинарник из корневой папки репозитория на бинарник на тот, который соответствует вашей архтектуре. \nПрограмма не является анонимизатором, она не меняет ваш IP-адрес и не отправляет ваш сетевой трафик через промежуточные сервера."
url: "https://github.com/x9132706292/hassos-addons/"
startup: "services"
boot: "auto"
arch:
  - i386
ports:
  999/tcp: 999
ports_description:
  999/tcp: "Proxy server port"
