name: "ByeDPI"
version: "2024"
slug: "byedpi"
description: "Docker - контейнер для обхода DPI. поднимает socks-proxy на 999 порту."
url: "https://github.com/x9132706292/hassos-addons/"
startup: "services"
boot: "auto"
arch:
  - i386
ports:
  999/tcp: 999
ports_description:
  999/tcp: "Proxy server port"
